#!/usr/bin/env python3
"""
Futu OpenD Mock Trading Handoff Script.

Reads an `order_spec.json` generated by StockBuddy and simulates placing
a mock order via the Futu OpenD local gateway.

Usage:
  python3 cli/futu_mock_handoff.py experiments/20250327T120000Z_ab12/order_spec.json
"""

import argparse
import json
import logging
import sys
from pathlib import Path

# Configure minimal logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def simulate_futu_handoff(spec_path: str) -> None:
    path = Path(spec_path).expanduser()
    if not path.is_file():
        logging.error("Cannot find file: %s", path.resolve())
        logging.error(
            "Use a real path (README 里的 path/to/ 只是占位). "
            "例如某次 pilot 产物: experiments/<run_id>/order_spec.json"
        )
        sys.exit(1)

    try:
        spec = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        logging.error(f"Failed to parse JSON: {e}")
        sys.exit(1)

    logging.info(f"--- Loaded Order Spec for Run {spec.get('run_id', 'unknown')} ---")

    blocked = spec.get("blocked_by_risk_gate")
    if blocked:
        logging.warning("Order blocked by Risk Gate. Handoff aborted.")
        logging.warning(f"Reason: {spec.get('gate_reason')}")
        return

    action = spec.get("action")

    if action != "BUY":
        logging.info(f"Action is {action}. No execution required for long-only mode.")
        return

    ticker = spec.get("ticker", "").replace(".HK", "")
    futu_ticker = f"HK.{ticker}"
    
    fraction = spec.get("position_fraction", 0.0)
    stop_loss = spec.get("stop_loss")
    take_profit = spec.get("take_profit")
    lot_adj = spec.get("target_shares_lot_adjusted")

    logging.info("--- Futu OpenD Context Initialized (Mock) ---")
    logging.info(f"[mock] futu.OpenQuoteContext(host='127.0.0.1', port=11111)")
    logging.info(f"[mock] futu.OpenHKTradeContext(host='127.0.0.1', port=11111)")
    
    logging.info(f"[mock] Fetching current quote for {futu_ticker}...")
    current_price = 100.0  # mock price
    logging.info(f"[mock] Current price: {current_price} HKD")
    
    account_value = 100000.0
    budget = account_value * fraction
    if lot_adj is not None and int(lot_adj) > 0:
        shares = int(lot_adj)
        logging.info(f"[mock] qty from target_shares_lot_adjusted={shares} (execution bridge v1)")
    else:
        shares = int(budget / current_price)
    
    logging.info("\n--- EXECUTING TRADE ---")
    print(f"trd_ctx.place_order(")
    print(f"    price={current_price},")
    print(f"    qty={shares},")
    print(f"    code='{futu_ticker}',")
    print(f"    trd_side=futu.TrdSide.BUY,")
    print(f"    order_type=futu.OrderType.NORMAL,")
    print(f"    trd_env=futu.TrdEnv.SIMULATE")
    print(f")")

    if stop_loss or take_profit:
        logging.info("\n--- SETTING CONDITION ORDERS ---")
        if stop_loss:
            sl_price = round(current_price * stop_loss, 2)
            print(f"# Stop Loss ({int((1 - stop_loss) * 100)}%):")
            print(f"trd_ctx.place_order(price={sl_price}, qty={shares}, code='{futu_ticker}', trd_side=futu.TrdSide.SELL, order_type=futu.OrderType.ABSOLUTE_LIMIT, ...)")
        
        if take_profit:
            tp_price = round(current_price * take_profit, 2)
            print(f"# Take Profit (+{int((take_profit - 1) * 100)}%):")
            print(f"trd_ctx.place_order(price={tp_price}, qty={shares}, code='{futu_ticker}', trd_side=futu.TrdSide.SELL, order_type=futu.OrderType.ABSOLUTE_LIMIT, ...)")

    logging.info("\n--- Handoff Complete ---")


def main():
    parser = argparse.ArgumentParser(description="Mock execute a StockBuddy order_spec.json via Futu API.")
    parser.add_argument("spec_path", help="Path to order_spec.json")
    args = parser.parse_args()
    simulate_futu_handoff(args.spec_path)


if __name__ == "__main__":
    main()